"""Report generation service for investigation cases."""
import json
from datetime import datetime
from typing import Dict, Any, Optional

class ReportService:
    """Generates case report drafts from investigation data."""

    @staticmethod
    def generate_report(case_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a structured case report draft."""
        report = {
            "title": "TrailGuard AI — Investigation Case Report Draft",
            "disclaimer": "Synthetic Demonstration Only — Human Review Required. "
                          "Risk indicators are generated from synthetic/demo data "
                          "and require human review before any real-world action.",
            "generated_at": datetime.utcnow().isoformat(),
            "case": {
                "case_number": case_data.get("case_number", "N/A"),
                "status": case_data.get("status", "open"),
                "severity": case_data.get("severity", "medium"),
                "title": case_data.get("title", "Untitled Case"),
                "risk_score": case_data.get("risk_score", 0),
                "created_at": str(case_data.get("created_at", "")),
                "updated_at": str(case_data.get("updated_at", "")),
            },
            "involved_accounts": case_data.get("accounts", []),
            "evidence": case_data.get("evidence", []),
            "transaction_timeline": case_data.get("transactions", []),
            "aml_findings": case_data.get("detections", []),
            "analyst_notes": case_data.get("notes", []),
            "narrative_summary": case_data.get("summary", "No narrative summary available."),
            "limitations": [
                "All data is synthetic/demo data only.",
                "Risk scores are generated by deterministic rules, not ML models.",
                "This report is a draft and requires human investigator review.",
                "Do not use this report as a filed Suspicious Activity Report (SAR).",
                "Legal and regulatory review is required before any real-world action.",
            ],
        }
        return report

    @staticmethod
    def render_html(report: Dict[str, Any]) -> str:
        """Render report as HTML string."""
        case = report["case"]
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{report['title']}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a2e; background: #f8f9fa; }}
h1 {{ color: #0a0e1a; border-bottom: 2px solid #06b6d4; padding-bottom: 10px; }}
h2 {{ color: #1c2440; margin-top: 30px; }}
.disclaimer {{ background: #fff3cd; border: 1px solid #ffc107; padding: 15px; border-radius: 8px; margin: 20px 0; }}
.meta {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #dee2e6; }}
th {{ background: #0a0e1a; color: white; }}
.footer {{ margin-top: 40px; font-size: 12px; color: #6c757d; text-align: center; }}
</style></head><body>
<h1>{report['title']}</h1>
<div class="disclaimer"><strong>{report['disclaimer']}</strong></div>
<div class="meta">
<h2>Case Metadata</h2>
<table><tr><th>Field</th><th>Value</th></tr>
<tr><td>Case Number</td><td>{case['case_number']}</td></tr>
<tr><td>Status</td><td>{case['status']}</td></tr>
<tr><td>Severity</td><td>{case['severity']}</td></tr>
<tr><td>Title</td><td>{case['title']}</td></tr>
<tr><td>Risk Score</td><td>{case['risk_score']}</td></tr>
</table></div>
<h2>Evidence</h2>
<table><tr><th>Type</th><th>Description</th></tr>"""
        for ev in report.get("evidence", []):
            html += f"<tr><td>{ev.get('evidence_type', 'N/A')}</td><td>{ev.get('description', 'N/A')}</td></tr>"
        html += "</table>"
        html += f"<h2>Narrative Summary</h2><p>{report['narrative_summary']}</p>"
        html += "<h2>Limitations</h2><ul>"
        for lim in report["limitations"]:
            html += f"<li>{lim}</li>"
        html += "</ul>"
        html += f'<div class="footer">Generated: {report["generated_at"]}</div>'
        html += "</body></html>"
        return html
