"""Add missing graph_metrics columns

Revision ID: e73325b8fd8b
Revises: 0001
Create Date: 2026-06-20 17:25:05.563557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e73325b8fd8b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_risk_assessments', 'analysis_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('account_risk_assessments', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'LOW'"))
    op.alter_column('account_risk_assessments', 'component_scores_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('account_risk_assessments', 'reason_codes_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'account_risk_assessments', 'analysis_runs', ['analysis_run_id'], ['id'])
    op.create_foreign_key(None, 'account_risk_assessments', 'accounts', ['account_id'], ['id'])
    op.alter_column('accounts', 'country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('accounts', 'account_age_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'365'"))
    op.create_foreign_key(None, 'accounts', 'datasets', ['dataset_id'], ['id'])
    op.alter_column('analysis_runs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('analysis_runs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'metrics_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_events', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('audit_events', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('audit_events', 'metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'audit_events', 'users', ['user_id'], ['id'])
    op.alter_column('case_evidence', 'evidence_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('case_evidence', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.create_foreign_key(None, 'case_evidence', 'investigation_cases', ['case_id'], ['id'])
    op.create_foreign_key(None, 'case_evidence', 'detection_events', ['event_id'], ['id'])
    op.alter_column('case_notes', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'case_notes', 'investigation_cases', ['case_id'], ['id'])
    op.create_foreign_key(None, 'case_notes', 'users', ['user_id'], ['id'])
    op.alter_column('datasets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('datasets', 'file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('datasets', 'row_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('datasets', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.create_foreign_key(None, 'datasets', 'users', ['user_id'], ['id'])
    op.alter_column('detection_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('detection_events', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('detection_events', 'reason_codes_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('detection_events', 'evidence_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'detection_events', 'analysis_runs', ['analysis_run_id'], ['id'])
    op.create_foreign_key(None, 'detection_events', 'datasets', ['dataset_id'], ['id'])
    op.add_column('graph_metrics', sa.Column('in_degree_centrality', sa.Float(), nullable=True))
    op.add_column('graph_metrics', sa.Column('out_degree_centrality', sa.Float(), nullable=True))
    op.add_column('graph_metrics', sa.Column('metrics_json', sa.JSON(), nullable=True))
    op.alter_column('graph_metrics', 'betweenness_centrality',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_degree',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'out_degree',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_total_value',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'out_total_value',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_unique_counterparties',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'out_unique_counterparties',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_cycle',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('graph_metrics', 'cycle_count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_graph_metrics_account_id'), 'graph_metrics', ['account_id'], unique=False)
    op.create_foreign_key(None, 'graph_metrics', 'analysis_runs', ['analysis_run_id'], ['id'])
    op.create_foreign_key(None, 'graph_metrics', 'accounts', ['account_id'], ['id'])
    op.alter_column('investigation_cases', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('investigation_cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('investigation_cases', 'risk_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('investigation_cases', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'investigation_cases', 'accounts', ['primary_account_id'], ['id'])
    op.create_foreign_key(None, 'investigation_cases', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'investigation_cases', 'users', ['created_by'], ['id'])
    op.alter_column('transactions', 'external_transaction_ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
    op.alter_column('transactions', 'channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'online'"))
    op.alter_column('transactions', 'sender_country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'receiver_country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'device_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('transactions', 'ip_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('transactions', 'scenario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('ix_transactions_amount', 'transactions', ['amount'], unique=False)
    op.create_index('ix_transactions_receiver', 'transactions', ['receiver_account_id'], unique=False)
    op.create_index('ix_transactions_sender', 'transactions', ['sender_account_id'], unique=False)
    op.create_index('ix_transactions_timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['receiver_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'datasets', ['dataset_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['sender_account_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_sender', table_name='transactions')
    op.drop_index('ix_transactions_receiver', table_name='transactions')
    op.drop_index('ix_transactions_amount', table_name='transactions')
    op.alter_column('transactions', 'scenario',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('transactions', 'ip_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'device_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'receiver_country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('transactions', 'sender_country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('transactions', 'channel',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'online'"))
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
    op.alter_column('transactions', 'external_transaction_ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'investigation_cases', type_='foreignkey')
    op.drop_constraint(None, 'investigation_cases', type_='foreignkey')
    op.drop_constraint(None, 'investigation_cases', type_='foreignkey')
    op.alter_column('investigation_cases', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('investigation_cases', 'risk_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('investigation_cases', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('investigation_cases', 'severity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.drop_constraint(None, 'graph_metrics', type_='foreignkey')
    op.drop_constraint(None, 'graph_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_graph_metrics_account_id'), table_name='graph_metrics')
    op.alter_column('graph_metrics', 'cycle_count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_cycle',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('graph_metrics', 'out_unique_counterparties',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_unique_counterparties',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'out_total_value',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_total_value',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'out_degree',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'in_degree',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('graph_metrics', 'betweenness_centrality',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('graph_metrics', 'metrics_json')
    op.drop_column('graph_metrics', 'out_degree_centrality')
    op.drop_column('graph_metrics', 'in_degree_centrality')
    op.drop_constraint(None, 'detection_events', type_='foreignkey')
    op.drop_constraint(None, 'detection_events', type_='foreignkey')
    op.alter_column('detection_events', 'evidence_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('detection_events', 'reason_codes_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('detection_events', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('detection_events', 'severity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.alter_column('datasets', 'error_message',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('datasets', 'row_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('datasets', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('datasets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'case_notes', type_='foreignkey')
    op.drop_constraint(None, 'case_notes', type_='foreignkey')
    op.alter_column('case_notes', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'case_evidence', type_='foreignkey')
    op.drop_constraint(None, 'case_evidence', type_='foreignkey')
    op.alter_column('case_evidence', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('case_evidence', 'evidence_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.alter_column('audit_events', 'metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_events', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_events', 'action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('audit_events', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('analysis_runs', 'metrics_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'error_message',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'account_age_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'365'"))
    op.alter_column('accounts', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'account_risk_assessments', type_='foreignkey')
    op.drop_constraint(None, 'account_risk_assessments', type_='foreignkey')
    op.alter_column('account_risk_assessments', 'reason_codes_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account_risk_assessments', 'component_scores_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account_risk_assessments', 'risk_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'LOW'"))
    op.alter_column('account_risk_assessments', 'analysis_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
